version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: asap-prometheus
    networks:
      - asap-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--enable-feature=agent'
      - '--web.external-url=/prometheus/'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

volumes:
  prom_data:

networks:
  asap-network:
    driver: bridge
    external: true